baseURL = "http://124.223.208.207/"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN" # 网站语言, 仅在这里 CN 大写
hasCJKLanguage = true # 是否包括中日韩文字
title = "Home"
description = "学点吧" # 网站描述
keywords = ["Blog", "Hugo"] # 网站关键词
theme = "DoIt" # 更改使用 Hugo 构建网站时使用的默认主题
defaultTheme = "light" #站默认主题样式 ("light", "dark", "black", "auto")
[params]
  version = "0.3.X"  # DoIt 主题版本
  images = ["/profile_photo.png"]

[params.home]
  rss = 50   # DoIt 新增 | 0.2.0 RSS 文章数目
  # 主页个人信息
  [params.home.profile]
    enable = true
    avatarURL = "/profile_photo.png"
    title = "Yexuan" # DoIt 更改 | 0.2.7 主页显示的网站标题 (支持 HTML 格式)
    #subtitle = "{{}}"
    
    typeit = false # 是否为副标题显示打字机动画
    social = true  # 是否显示社交账号
    disclaimer = "" # DoIt 新增 | 0.2.0 免责声明 (支持 HTML 格式)
  # 主页文章列表
  [params.home.posts]
    enable = true
    paginate = 10 # 主页每页显示文章数量
    # DoIt 删除 | 0.2.0 被 params.page 中的 hiddenFromHomePage 替代
    # 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
    defaultHiddenFromHomePage = false

[author]
name = "yexuan"
email = "yexuan.d@qq.com"

# 用于 Hugo 输出文档的设置
[outputs]
  # DoIt 更改 | 0.2.0
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[params.search]
  enable = true
  type = "fuse"   # 搜索引擎的类型 ("algolia", "fuse")
  contentLength = 4000   # 文章内容最长索引长度
  placeholder = ""   # 搜索框的占位提示语
  maxResultLength = 10   # DoIt 新增 | 0.2.1 最大结果数目
  snippetLength = 10   # DoIt 新增 | 0.2.3 结果内容片段长度
  highlightTag = "em"   # DoIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
  absoluteURL = false   # DoIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
  [params.search.fuse]
  #  https://fusejs.io/api/options.html
    isCaseSensitive = false     # 是否应区分大小写
    minMatchCharLength = 2
    findAllMatches = false
    location = 0
    threshold = 0.3
    distance = 100
    ignoreLocation = false
    useExtendedSearch = false
    ignoreFieldNorm = false

[params.page]
    # DoIt 新增 | 0.2.0 是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    # DoIt 新增 | 0.2.0 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false
    # DoIt 新增 | 0.2.0 是否使用 twemoji
    twemoji = false
    # 是否使用 lightgallery
    lightgallery = false
    # DoIt 新增 | 0.2.0 是否使用 ruby 扩展语法
    ruby = true
    # DoIt 新增 | 0.2.0 是否使用 fraction 扩展语法
    fraction = true
    # DoIt 新增 | 0.2.0 是否使用 fontawesome 扩展语法
    fontawesome = true
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = true
    # DoIt 新增 | 0.2.14 配置文章原始文件的链接
    linkToSource = false
    # "https://github.com/user/repo/blob/main/{path}"
    # DoIt 新增 | 0.2.13 配置编辑文章的链接
    linkToEdit = false
    # "https://github.com/user/repo/edit/main/{path}"
    # "https://gitlab.com/user/repo/-/edit/main/{path}"
    # "https://bitbucket.org/user/repo/src/main/{path}?mode=edit"
    # DoIt 新增 | 0.2.14 配置提交错误的链接
    linkToReport = false
    # "https://github.com/user/repo/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/user/repo/blob/main/{path}|"
    # DoIt 新增 | 0.2.4 是否在 RSS 中显示全文内容
    rssFullText = false
    # DoIt 新增 | 0.2.13 是否在文章开头显示系列导航
    seriesNavigation = true
    # 是否启用最后修改时间
    enableLastMod = true
    # 是否启用字数统计
    enableWordCount = true
    # 是否启用阅读时间估计
    enableReadingTime = true
    # DoIt 新增 | 0.2.13 过时文章提示
    [params.page.outdatedArticleReminder]
      enable = true
      # 如果文章最后更新于 90 天之前，显示提醒
      reminder = 90
      # 如果文章最后更新于 180 天之前，显示警告
      warning = 180
    # DoIt 新增 | 0.2.0 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # DoIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
      keepStatic = false
      # 是否使侧边目录自动折叠展开
      auto = true
    # DoIt 新增 | 0.2.0 代码配置
    [params.page.code]
      # 是否显示代码块的复制按钮
      copy = true
      # 默认展开显示的代码行数
      maxShownLines = 10
    # DoIt 新增 | 0.2.14 表格配置
    [params.page.table]
      # 是否开启表格排序
      sort = true
  [params.footer]
      enable = true
      # DoIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
      custom = """<a href="https://beian.mps.gov.cn/#/query/webSearch" target="_blank">沪公网安备31011302007515号</a>"""
      # DoIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
      hugo = true
      # DoIt 新增 | 0.2.14 托管服务信息 (支持 HTML 格式)
      # <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>
      hostedOn = ''
      # DoIt 新增 | 0.2.0 是否显示版权信息
      copyright = true
      # DoIt 新增 | 0.2.0 是否显示作者
      author = true
      # 网站创立年份
      since = 2023
      # ICP 备案信息, 仅在中国使用 (支持 HTML 格式)
      icp = """<a href="https://beian.miit.gov.cn/" target="_blank">皖ICP备2023023596号</a>"""
      # 许可协议信息 (支持 HTML 格式)
      # license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.page.math]
  enable = true
  # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
  blockLeftDelimiter = ""
  blockRightDelimiter = ""
  # 默认行内定界符是 $ ... $ 和 \\( ... \\)
  inlineLeftDelimiter = ""
  inlineRightDelimiter = ""
  # KaTeX 插件 copy_tex
  copyTex = true
  # KaTeX 插件 mhchem
  mhchem = true
[params.page.comment]
    enable = true
    # Gitalk 评论系统设置
    # {{< link "https://github.com/gitalk/gitalk" Gitalk >}} comment config
    [params.page.comment.gitalk]
      # DoIt 新增 | 0.1.1
      enable = true
      owner = "yexuan333"
      repo = "BlogGitTalKAPPK"
      clientId = "a6999600781701d4e9a3"
      clientSecret = "7d6a82ec2b58a2253b9b174f21ceb99dd78f6a8e"

  [params.sponsor]
    enable = false
    bio = "如果你觉得这篇文章对你有所帮助，欢迎赞赏~"
    link = "https://www.buymeacoffee.com" # 你的赞赏页面的地址
    custom = "" # 自定义 HTML

[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "全部文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "series"
    pre = ""
    post = ""
    name = "系列"
    url = "/series/"
    title = ""
    weight = 2
  # [[menu.main]]
  #   identifier = "tags"
  #   pre = ""
  #   post = ""
  #   name = "标签"
  #   url = "/tags/"
  #   title = ""
  #   weight = 2
  # [[menu.main]]
  #   identifier = "categories"
  #   pre = ""
  #   post = ""
  #   name = "分类"
  #   url = "/categories/"
  #   title = ""
  #   weight = 3
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
series = "series"
# Hugo 解析文档的配置
[markup]
  # 语法高亮设置
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false 是必要的设置
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
